### ISSUE TITLE
somatic calling error 35

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [AstraZeneca-NGS/VarDict#41] opened 2017-02-06 16:47 UTC
Hi!!
I have use this comand in somatic:

`/illumina/software/PROG2/VarDict/vardict -G /illumina/software/database/database_2016/hg19_primary.fa -f 0.01  -N 415_tumor -b "/mnt/ALIGN/415/Coclean/415.sorted.dup.recal.cleaned.bam|/mnt/ALIGN/415/Coclean/416.sorted.dup.recal.cleaned.bam" -c 1 -S 2 -E 3 -g 4 /illumina/software/database/database_2016/TARGET/BED_chromosome/my.chr12.bed| testsomatic.R |var2vcf_paired.pl -N "415_tumor|416_normal" -f 0.01 -v 5  > 415_416_vardict_chr12.vc`

Now I use to divede my exome  bed on chromosome but I have this error;:
```
`
Use of uninitialized value in concatenation (.) or string at /illumina/software/PROG2/VarDict/var2vcf_paired.pl line 3`5.

```
What is right way to do somatic calling with the new version
thanks so much!

**Comment by mjafin** [comment] 2017-02-06 18:20
You can typically ignore those warnings. It should still run through. They can be caused by improper CIGAR strings if you used an explicit indel realigner (which we recommend against).

**Comment by bioinfo-dirty-jobs** [comment] 2017-02-07 08:36
No the script stops...
the problems remain..it is not closed

**Comment by bioinfo-dirty-jobs** [comment] 2017-02-07 08:38
The first part of script gave me a results but  testsomatic.R and var2vcf_paired.pl  not working

**Comment by mjafin** [comment] 2017-02-07 09:04
Sorry I was too quick to close the issue. What error do you get in `testsomatic.R`? Maybe that's a clue. And also what's the last line in the text file from the first step - maybe that's close to the problem region. 

Is there any way you could access a more recent cluster? By running VarDict via bcbio would really help you focus on what's important, i.e. interpreting the data and not debugging algorithms..

**Comment by bioinfo-dirty-jobs** [comment] 2017-02-07 09:12
Thanks so much for the help. Unfortunately I can't use that.
So the first step work without error:

`415_tumochr12   133810869-1338101338108690942   G	A	144153	90	0	1	G/A	0.0069	2;0	41.0	0	30.0	0	60.0	2.000	0.0072	0	1.0	152	2	45	105	1	1	G/A	0.0132	2;2	29.5	1	30.0	1	60.0	4.000	0.0138	0	1.0	0	1.000	1	AGTCCCGGCACAGTCTGCCC	CAAGGGTCACCAGCTCCGCC	chr12:133810692-133810942	LikelyLOH	SNV`

the problems is when I use testsomati.R there is not error but don't gave eany type of error:

I try also this:
```

cat 415_416_vardict_chr12.vcf |testsomatic.R  
[sbsuser@compute-00-00 Prova3]
```$

**Comment by mjafin** [comment] 2017-02-07 09:20
Just to clarify, `415_416_vardict_chr12.vcf` is not a vcf file but the output of the first VarDict command, right? I.e. a tab delimited file like the one you pasted above (`415_tumochr12 133810869-1338101338108690942 ...`)? `testsomatic.R` doesn't operate on vcf files but text files.

If this is the case, then I'm confused as `testsomatic.R` should output as many lines as it sees in the input. I wonder if you open R manually, read a text file from VarDict and check what the R script is doing. Maybe that gives you a clue as to why there is no output.

**Comment by bioinfo-dirty-jobs** [comment] 2017-02-07 09:37
So I try to use .txt not vcf but not change the results. It is a txt file tab delimited.
So I try to debug the data but I have one error:
 ```
<- read.table( "415_416_vardict_chr12.vcf", sep = "\t", header = F, colClasses=c("character", NA, NA, NA, NA, "character", "character", NA, NA, NA, NA, NA, NA, "character", NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "character", NA, "character",  NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "character", "character", "character", "character"))
Error in scan(file, what, nmax, sep, dec, quote, skip, nlines, na.strings,  : 
  line 1 did not have 50 elements

```
So the first error is the expect 50 columns but obtain 51. Why this difference?

**Comment by mjafin** [comment] 2017-02-07 09:52
Would you be able drop a file of, say, the ten first entries here (`head -n10 415_416_vardict_chr12.vcf > test.txt`)?

**Comment by bioinfo-dirty-jobs** [comment] 2017-02-07 09:54
All the rows have 51 rows...

**Comment by mjafin** [comment] 2017-02-07 09:56
If you don't want to share your data, can you try running VarDictJava to output the initial text file and see if it also has 51 columns? You need Java version 8. Further, please paste the entire java command here.

**Comment by bioinfo-dirty-jobs** [comment] 2017-02-07 11:00
So if I use  the java version for the first 10 lines seem work.. Ok whit this comand work

`/illumina/software/PROG2/VarDictJava-1.4.8/bin/VarDict -G /illumina/software/database/database_2016/hg19_primary.fa -f 0.01  -N 415_tumor -b "/mnt/ALIGN/415/Coclean/415.sorted.dup.recal.cleaned.bam|/mnt/ALIGN/415/Coclean/416.sorted.dup.recal.cleaned.bam" -c 1 -S 2 -E 3 -g 4 /illumina/software/database/database_2016/TARGET/BED_chromosome/my.chr22.bed|/illumina/software/PROG2/VarDictJava-1.4.8/VarDict/testsomatic.R |/illumina/software/PROG2/VarDictJava-1.4.8/VarDict/var2vcf_paired.pl -N "415_tumor|416_normal" > provami_tomerge.vcf`

However if I send this command using qsub I have some errors but this is another  problem... So I post another ticket..thanks so much!! So there is a problem on the perl script...
Thanks so much!

**Comment by mjafin** [comment] 2017-02-07 11:20
Well good to hear Java gives you the correct output. It's 20x faster than the Perl script anyways and we're in the process of deprecating support for the Perl version. 

One quick question, are you defaulting to bash shell? When we were using CentOS5 for some reason the default was tcsh or some other exotic shell. They spell trouble, so I suggest defaulting to bash in case you're not.

Regarding SGE and other queuing systems I'm afraid they're outside the scope of our support for VarDict.

**Closed by mjafin** 2017-02-07 11:20 UTC
