### ISSUE TITLE
several warnings: Use of uninitialized value, Use of uninitialized value in join or string

### ISSUE THREAD

**Issue by corneliabuus** [AstraZeneca-NGS/VarDict#139] opened 2020-02-13 08:50 UTC
I have a problem when trying to run VarDict on phage data. It gives a lot of the same errors, for what looks like every line in our bam,bed or fasta file. 
![Skærmbillede 2020-02-13 kl  09 45 45](https://user-images.githubusercontent.com/50442541/74416647-bbe0c000-4e45-11ea-9df8-422173265fad.png) 
I've tried to looking into every file and made sure they are indexed, but we can't seem to find a problem.

**Comment by PolinaBevad** [comment] 2020-02-13 08:58
Hi @corneliabuus , 
Sorry that you have a problem!

What version of VarDict do you use? It seems that it is not the last one (1.6.0 or master branch version). I recommend trying to upgrade it to the master branch version first.
Also, can you please provide a command line with options that you use when running VarDict?

**Comment by corneliabuus** [comment] 2020-02-13 09:49
We just cloned it, with the following: git clone --recursive https://github.com/AstraZeneca-NGS/VarDict, so I think it's the latest.

our command line look like this:  

#!/bin/bash

AF_THR="0.01" # minimum allele frequency
	
VarDict/vardict -G NC_007019.1.fa -f $AF_THR -N W1T1 -b W1T1.sorted.bam -c 1 -S 2 -E 3 -g 4 W1T1.bed | VarDict/teststrandbias.R | VarDict/var2vcf_valid.pl -N W1T1 -E -f $AF_THR > W1T1.vcf

**Comment by PolinaBevad** [comment] 2020-02-13 10:03
Okay, thank you for checking! Can you please provide a small slice of your BAM file where it is reproduced so I can check what is the problem?

**Comment by corneliabuus** [comment] 2020-02-13 10:15
Yes thank you for helping.  I've sendt you a mail with a picture of a slice of the bam file.

**Comment by PolinaBevad** [comment] 2020-02-18 13:17
As we discussed in emails, the reason was incorrect locale, which can cause problems in both versions. 
Thank you, I'll close the issue!

**Closed by PolinaBevad** 2020-02-18 13:17 UTC
