### ISSUE TITLE
empty output for PE sequence

### ISSUE THREAD

**Issue by tbmorrison** [AstraZeneca-NGS/VarDict#61] opened 2018-04-20 18:22 UTC
I'm attempting to implement Vardict as part of an analysis plan for the FDA's SEQ QC targeted sequencing work group.  I'm getting an empty output from PE hybrid capture sequences when using VarDict-1.5.1.  I used bwa for alignment with the -f P flag to ensure outputs are paired and mapped.  I used BaseRecalibrator to tune the Q scores and then sort and index with samtools.  The resulting files give good VCF results from mpileup, and mutect2 VCF.  

The command line below runs for a second and exists with no error or data in the output file.
VarDict -b sample4rep2_S8.sorted.corr.bam -G /NGS/REFS/genome.fa -N sample4rep2_S8 -f 0.01 -v -c 1 -S 2 -E 3 -th 8 /NGS/MIX2.bed > sample4rep2_S8.vardict.txt

I can't get the Java VarDict version to install to see if an alternative version works (gradle error involving an issue with slf4j logger).

As per one suggestion in this forum, I reduced the bed file down to 3 small regions that have known VAF of >20%.  Still empty output.

I've also tried removing -th 8 flag, adding -g 4 flag.  I'm running Ubuntu AWS server using 16 processors x 64 Gb mem.

**Comment by chapmanb** [comment] 2018-04-25 00:51
Sorry about the issues here. I'm not totally sure what is going wrong and why you're seeing issues with VarDict relative to mutect2 and plain old pileup. A couple of questions/suggestions:

- I'm not sure what you mean by `-f P` to bwa. Could you expand a bit on how you're mapping?
- It would be worth trying vardict-java and using bioconda (https://bioconda.github.io/#using-bioconda) would help avoid your build issues. You can use miniconda then `conda install -c conda-forge -c bioconda vardict-java`. It would be useful to know if this helps resolve the issue compared to the perl version.
- If you're still having issues, are you able to share the minimal input that produces empty input? Maybe we could debug/spot issues from there.

Thanks for helping debug the problem.

**Comment by tbmorrison** [comment] 2018-04-25 16:41
_I'm not sure what you mean by -f P to bwa. Could you expand a bit on how you're mapping?_
-f P ensures all output alignments are paired and mapped.  I only added this when troubleshooting VarDict.  I reprocessed without this tag and got same empty file.

_It would be worth trying vardict-java and using bioconda_
I installed vardict-java using bioconda.  This did not help, I still get empty file.

_Share minimum input_
I've pasted URLs to the files below.  I'm using hg38 as reference genome (if you want the reference genome files, let me know which ones in particular).
https://s3.amazonaws.com/accugenomicsbucket/MIX4a.bed
https://s3.amazonaws.com/accugenomicsbucket/sample4rep2_S8.sorted.corr.bam
https://s3.amazonaws.com/accugenomicsbucket/sample4rep2_S8.sorted.corr.bam.bai

**Comment by tbmorrison** [comment] 2018-05-21 14:44
Very helpful!  The pipeline I'm implementing uses gatk4 BaseRecalibrator to adjust the Q scores and I did not realize how significantly the scores were adjusted.

**Comment by PolinaBevad** [comment] 2019-05-28 10:34
@tbmorrison, hello!
I will close this issue because it was solved by changing quality filter.
Thanks for posting and thanking Brad Chapman for finding the cause of the problem!

**Closed by PolinaBevad** 2019-05-28 10:34 UTC
