### ISSUE TITLE
vardict.pl - use of uninitialized value

### ISSUE THREAD

**Issue by ALFLAG** [AstraZeneca-NGS/VarDict#85] opened 2018-09-21 15:22 UTC
Good Evening,

I was trying Vardict (perl version), and I was facing the same problem as other regarding the creation of 36 columns output file and a teststranbiais.R script that was accepting only 34 or 38 columns. This problem is solved, and I thank you for that.
However, despite the fact that the program seams to work well, using vardict.pl script I noticed a message that arose several times:
```Use of uninitialized value in hash element at /home/alflag/miniconda3/envs/vardict/bin/vardict line 1158, <SAM> line 708.```

I would like to know the reason(s) of such answers, and if it will compromise the output file.
Thanks to all.

Regards,

Alex

**Comment by PolinaBevad** [comment] 2018-09-25 12:07
@ALFLAG, hello!
Such errors can compromise the output sometimes. So we have to investigate them closer.
Could you please upload the small part for BAM and the command you used, which causes such an error? We will try to reproduce it.

**Comment by ALFLAG** [comment] 2018-10-03 14:34
Hello @PolinaBevad !
I am terribly sorry for this very late answer.
unfortunatly, I will not be able to communicate my data, even a part of it.
For the record, I tried to use vardict multiple times on different datasets, and I was not able to replicate the warning message, excepted of course, with the one I evoked in the first post.
I removed the problematic lines in my bam file (only four reads were problematic), and the problem disappeared.

Thank you for your time.

Regards,

@ALFLAG

**Comment by PolinaBevad** [comment] 2018-10-08 14:44
@ALFLAG, thank you for the answer!
I looked at this part of the code and didn't see any values that can be unitialized on 1158 line of vardict.pl. Maybe you use an old version of Vardict?
I will close the issue, but you can re-open it if you will be able to upload part of other problematic bam to found out the reason. 
Thank you again.

**Closed by PolinaBevad** 2018-10-08 14:44 UTC
