### ISSUE TITLE
vardict running extremely slow on 10G targeting sequencing data   

### ISSUE THREAD

**Issue by MIAOKUI** [AstraZeneca-NGS/VarDict#49] opened 2017-08-08 07:24 UTC
Hi 
When we running on 10G targeting sequencing on ffpe source sample on pair mode, vardict running extremely slow compare to cf source sample.  The average coverage after dup removed about 1200x, I wondering why?

Because of cf source sample , even more data, I could be faster then ffpe.

**Comment by mjafin** [comment] 2017-08-08 07:46
Hi @MIAOKUI without knowing more about your data it's difficult to tell what the problem is. Can you try VarDictJava in place of `vardict.pl` and see if it speeds things up for you?

Can you explain further what you mean by 10G targeting and cf source sample?

**Comment by MIAOKUI** [comment] 2017-08-08 09:01
[Total] Raw Reads (All reads)	77500234
                                       [Total] QC Fail reads	0
                                        [Total] Raw Data(Mb)	10395.33
                                        [Total] Paired Reads	77500234
                                        [Total] Mapped Reads	77273209
                            [Total] Fraction of Mapped Reads	99.71%
                                     [Total] Mapped Data(Mb)	10361.37
                         [Total] Fraction of Mapped Data(Mb)	99.67%
                                     [Total] Properly paired	70970713
                         [Total] Fraction of Properly paired	91.57%
                                [Total] Read and mate paired	77074478
                    [Total] Fraction of Read and mate paired	99.45%
                                          [Total] Singletons	198731
                       [Total] Read and mate map to diff chr	7648614
                                               [Total] Read1	38391358
                                               [Total] Read2	39108876
                                        [Total] Read1(rmdup)	26286261
                                        [Total] Read2(rmdup)	26255841
                                [Total] forward strand reads	38885091
                               [Total] backward strand reads	38388118
                                 [Total] PCR duplicate reads	19374411
                     [Total] Fraction of PCR duplicate reads	25.07%
                            [Total] Map quality cutoff value	20
                       [Total] MapQuality above cutoff reads	70082080
                 [Total] Fraction of MapQ reads in all reads	90.43%
              [Total] Fraction of MapQ reads in mapped reads	90.69%
                                       [Target] Target Reads	44079660
              [Target] Fraction of Target Reads in all reads	56.88%
           [Target] Fraction of Target Reads in mapped reads	57.04%
                                    [Target] Target Data(Mb)	5187.57
                              [Target] Target Data Rmdup(Mb)	3395.32
                [Target] Fraction of Target Data in all data	49.90%
             [Target] Fraction of Target Data in mapped data	50.07%
                                      [Target] Len of region	2978808
                                      [Target] Average depth	1741.49
                               [Target] Average depth(rmdup)	1139.83
                                     [Target] Coverage (>0x)	99.94%
                                   [Target] Coverage (>=30x)	99.67%
                                  [Target] Coverage (>=100x)	98.43%
                                  [Target] Coverage (>=500x)	86.14%
                                 [Target] Coverage (>=1000x)	67.84%
                                 [Target] Coverage (>=2000x)	34.63%
                                [Target] Target Region Count	8747
                                [Target] Region covered > 0x	8740
                       [Target] Fraction Region covered > 0x	99.92%
                     [Target] Fraction Region covered >= 30x	99.82%
                    [Target] Fraction Region covered >= 100x	99.11%
                    [Target] Fraction Region covered >= 500x	89.47%
                   [Target] Fraction Region covered >= 1000x	68.77%


Above is the basic qc information about our data. 
Including all the some qc details

**Comment by MIAOKUI** [comment] 2017-08-08 09:04
ffpe means, the samples was extracted from tissue
cf means, the samples DNA  extracted blood plasma, basically cell free DNA. 
Sometime in order to detect somatic mutation in plasma, we sequencing about 20G. 
For ffpe, we sequence about 10G, but 10G runs for more slower then 20G  in pair mode with white cell as control.

**Comment by mjafin** [comment] 2017-08-08 09:10
Do you mean you sequence 10 million reads (10G) per sample for your panel?

In any case, please try VarDictJava to see if it speeds things up for you.

**Comment by MIAOKUI** [comment] 2017-08-08 09:30
OK I will try and see how 
Thanks a lot

**Comment by MIAOKUI** [comment] 2017-08-08 09:31
Yes 10 million reads

**Comment by PolinaBevad** [comment] 2019-04-17 14:04
@MIAOKUI, hello!
I will close this issue because I believe that the version of VarDictJava met your needs about the time of processing. If you will have any questions, please, create an issue!
Thanks!

**Closed by PolinaBevad** 2019-04-17 14:04 UTC
