### ISSUE TITLE
vardict did not combine nearby SNVs

### ISSUE THREAD

**Issue by lituan** [AstraZeneca-NGS/VarDict#64] opened 2018-05-23 02:41 UTC
Hi, I encounter a complex mutation, which is composed of two SNVs, which is separated by one bp,  but vardict did not report this as a complex mutation 

reference  ACC
read          TCT

**Comment by PolinaBevad** [comment] 2019-04-17 13:42
@lituan, hello!
Sorry for the late reply!
There were updates regarding your question in the last version of VarDict, and now SNVs a combined better. Perhaps you can try the last version and if the problem repeats, please, provide the BAM file fragment to reproduce it.

**Comment by andurill** [comment] 2019-04-30 21:47
Hi, I've also encountered this issue before. Specifically, vardict does not combine SNPs that are separated by one or more base pairs (user defined by -X parameter) into a complex variant. This isn't if one or more of the complex variant is an indel. You mentioned above that the latest version of VarDict address this issue. Could you please clarify whether its the perl or the java version? And, could you please specify the release version? Thanks a lot!

**Comment by PolinaBevad** [comment] 2019-05-01 07:27
@andurill, hello!
It will be great if you can check this on master branch from Perl version (i.e. this commit: https://github.com/AstraZeneca-NGS/VarDict/commit/0d5315e005664673dae1d4bf859e48439010da6f). The changes about MNV were made in October 2018.
If it will reproduce, could you please share the small part of BAM for one of such cases? It will be very helful! 
Thank you!

**Comment by PolinaBevad** [comment] 2019-11-29 12:45
Hi @andurill, since you created another issue, maybe you can take a look at this one? :) 
Have you checked if this appears on new versions of VarDict? I did not find such cases, so if you succeeded, let me know!
Thank you!

**Comment by andurill** [comment] 2019-11-29 23:59
Hi @PolinaBevad , when you had suggested that I try the perl version to address this issue, I had some difficulties setting up and running Vardict perl on our server and in the midst of other tasks, I completely forgot about this ticket. Apologies.

I tested VardictJava_1.5.8 on several complex variants, and this vardict does seem to call MNVs properly (based on the argument provided to the '-X' parameter). So, I understand that the changes concerning MNVs in the perl version has been added to the VardictJava?

I have attached two screenshots and the corresponding mutation calls by Vardict.
<img width="351" alt="MNV1" src="https://user-images.githubusercontent.com/12943340/69892945-0dfb5600-12d9-11ea-886e-3ed8deab9ce6.png">

`17	7578448	.	GCCAT	CCCAG	253	PASS	STATUS=StrongSomatic;SAMPLE=TEST;TYPE=Complex;DP=997;VD=209;AF=0.2096;SHIFT3=0;MSI=2.000;MSILEN=1;SSF=0;SOR=0;LSEQ=GCTGTGACTGCTTGTAGATG;RSEQ=GGCGCGGACGCGGGTGCCGG	GT:DP:VD:ALD:RD:AD:AF:BIAS:PMEAN:PSTD:QUAL:QSTD:SBF:ODDRATIO:MQ:SN:HIAF:ADJAF:NM	0/1:997:209:87,122:279,498:777,209:0.2096:2,2:24.2:1:32.9:1:0.14649:1.27:60:208:0.2125:0.0231:1.9	0/0:308:0:0,0:74,234:308,0:0:2,0:23.2:1:31.5:1:1:0:60:60.6:1:0:0.1`

<img width="226" alt="MNV2" src="https://user-images.githubusercontent.com/12943340/69892956-24a1ad00-12d9-11ea-8315-cec8cf259eb6.png">

`9	21971199	.	CATC	TATT	204	PASS	STATUS=StrongSomatic;SAMPLE=TEST;TYPE=Complex;DP=443;VD=133;AF=0.3002;SHIFT3=0;MSI=2.000;MSILEN=3;SSF=0;SOR=0;LSEQ=GCCACTCGGGCGCTGCCCAT;RSEQ=ATGACCTGCCAGAGAGAACA	GT:DP:VD:ALD:RD:AD:AF:BIAS:PMEAN:PSTD:QUAL:QSTD:SBF:ODDRATIO:MQ:SN:HIAF:ADJAF:NM	0/1:443:133:26,107:50,242:292,133:0.3002:2,2:25.7:1:29:1:0.5856:1.18:41:9.231:0.2906:0.0497:2.3	0/0:204:0:0,0:36,167:203,0:0:0,0:0:0:0:0:1:0:0:0:0:0:0`

The vardict command I used in both cases:

`../vardict/VERSIONS/VarDictJava_1.5.8/build/install/VarDict/bin/VarDict -th 10 -G Homo_sapiens_assembly19.fasta -N TEST -b "Tumour.bam|Normal.bam" -f 0.02 -C -z 1 -u -c 1 -g 4 -S 2 -r 1 -E 3 -X 5 -x 2000 Variant.bed | ../vardict/VERSIONS/VarDictJava_1.5.8/build/install/VarDict/bin/testsomatic.R | ../vardict/VERSIONS/VarDictJava_1.5.8/build/install/VarDict/bin/var2vcf_paired.pl -N TEST -f 0.02`

Thank you so much for implementing this feature in Vardict Java!

**Comment by andurill** [comment] 2019-11-30 00:05
@PolinaBevad  An unrelated question: Is it possible to add Vardict version used to the output vcf? I believe vcf4.3 allows that. Something like `##source=VarDict_v1.5.8` immediately following the line `##fileformat=VCFv4.3`? I think having the version included in the vcf will be useful during testing/validation.

**Comment by PolinaBevad** [comment] 2019-12-02 07:04
@andurill , yes, I think we can make it. Thanks for the offer!

**Comment by PolinaBevad** [comment] 2019-12-12 10:50
Hi @andurill , I will close the issue because I added PR for version numbers in VCF: https://github.com/AstraZeneca-NGS/VarDict/pull/136

**Closed by PolinaBevad** 2019-12-12 10:50 UTC
