### ISSUE TITLE
I put the same Bam file as input, but the results are different

### ISSUE THREAD

**Issue by hunseong** [AstraZeneca-NGS/VarDict#56] opened 2017-12-14 10:27 UTC
Dear all

I am doing Variant calls using Vardict. However, even when the same Bam file was used, a problem that a specific variation was not detected in one Bam file occurred.

chr 13 : 32912299

vardict version : 1.4.7

mapping : bwa-0.7.12

dedup : picard--1.92

read_analysis & Indel call : GenomeAnalysisTKLite-2.3-9.jar

I do not know why I get different results from the same file.

vardict \
    -G $reference \
    -f 0.03 \
    -b $bam_file \
    -c 1 -S 2 -E 3 -g 4 \
    $target | $teststrandbias | \

This is a vardict option. I also have the same options. There is no difference in the Bam file.

What happened?

Thanks for the help,

hunseong.

**Comment by nkarulin** [comment] 2017-12-14 13:37
Hello, @hunseong!
Do you mean, you have launched VarDict two times sequentially on the same file with the same options and the results differ?

**Comment by hunseong** [comment] 2017-12-15 00:45
hi nkarulin

yes. I analyzed the same process twice with the same file, but once it was called and not once.

Why is the result different?

hunseong

**Comment by nkarulin** [comment] 2017-12-15 11:17
@hunseong, could you please provide some data, so we could reproduce those unexpected results?
Are you sure that `$target` variable has not been changed between launches?

Also, you could try Java VarDict implementation (https://github.com/AstraZeneca-NGS/VarDictJava). Does the difference appear with the Java version?

**Comment by hunseong** [comment] 2018-01-09 07:54
hi nkarulin
Sorry. I had a different schedule and my answer was late.

I want you to test it with a sample I have.
I would like to receive an email address to send a sample.
I will send the analysis option with the sample.

thank you,
hunseong

**Comment by nkarulin** [comment] 2018-01-09 11:36
Hello, @hunseong!
Please send data and launch options on my email: Nikolai_Karulin@epam.com

**Comment by nkarulin** [comment] 2018-01-12 12:47
@hunseong, thank you for the data.

Cold you please describe launch scenario in more details. What is the environment? Is sequential launching of vardict in the same environment is the case? How many launches have you had before it becomes clear that results differ?
On which step do you see the difference? Are you sure the difference is after vardict step? 

I have launched vardict with your BAM and with synthetic BED automatically for 10 times (without annotation step). And output does not differ. Could you please also provide BED file with regions? Are BED file also the same for all your launches?

Also didn't you try VarDictJava? It will work with the same set of arguments and much faster (also you could use `-th [threads]` option to launch it on several cores, that's even more faster). Please try it to see if the problem does or does not appear.

**Comment by hunseong** [comment] 2018-01-19 04:19
Hi Karulin,
 
I'm sorry I answered to late.
 
This analysis was run in a Linux environment, with different results in the same process.Also, I tried more than 5 time. I'll attach a bed file.-----Original Message-----

**Comment by nkarulin** [comment] 2018-02-01 14:10
Hi, @hunseong!
Have got your data, thanks

I am sorry, but it is really unlikely that VarDict could proceed nondeterministically in a single-thread mode. Multiple testing of your data show no difference in results of hundreds of launches. 

Are you sure the difference is after vardict step, not after snpEff or something?
Don't trying VarDictJava solve the problem?

**Comment by PolinaBevad** [comment] 2019-05-20 10:03
@hunseong, hello!
Sorry for the late reply, but we find few cases in the code that can cause non-deterministic behavior in the realignment step. Most of them appeared when working with soft clips. It was fixed in the last version of vardict.pl script (https://github.com/AstraZeneca-NGS/VarDict/commit/fb9bcab9daa2770cd48d9fcc210ccb61c8ea3a48 and it is merged in master branch), but not released yet. We made testing on several public datasets and didn't find any other problems.

I can't use your data for the test because the links are out-of-date. If it is possible you can try a new version and let us know if any other different results will appear.

**Comment by PolinaBevad** [comment] 2019-06-05 13:28
@hunseong, hello! 

I'll close the issue because in our opinion the problem was fixed. The new release (1.6) contains these changes. 
Thank you!

**Closed by PolinaBevad** 2019-06-05 13:28 UTC

**Comment by hunseong** [comment] 2019-06-10 08:49
hello, 
 
Thank you for solving the problem. 
 
I will use the new version and give feedback. 
 
thank you, good luck.
 
-----Original Message-----
