### ISSUE TITLE
Vardict table has lines with different number of columns

### ISSUE THREAD

**Issue by BilyanaStoilova** [AstraZeneca-NGS/VarDict#72] opened 2018-07-23 16:03 UTC
Hi,
I am trying to run Vardict on WES data from paired tumour and germline sample. I used BWA mem for alignment. However, when I pipe the Vardict code I get an empty vcf file in the end. Here is my script:
vardict -G Homo_sapiens_assembly38.fasta -f 0.05 -N CM0403_1-tumour -b "CM0403_1-tumour.bam|CM0403_1-control.bam" -c 1 -S 2 -E 3 -g 4 S07604514_Padded_full_hg38.bed | testsomatic.R | var2vcf_paired.pl -N "CM0403_1-tumour|CM0403_1-control" -f 0.05 > vardict_CM0403_1.vcf
Then I tried running the three different scripts of the code separately so that I try to pinpoint the problem. testsomatic.R produced the empty file. What I realised is that some of the lines in the text file produced by vardict which is the input for testsomatic.R have a different number of columns - it seems as if these lines went out of sync. You can see this in the attached file lines 143, 368, 478. These are always lines with StrongLOH filter, however not all lines with StrongLOH filter have this issue. Could you please help me figure out what is the problem and advice me how to solve it - for the moment I did grep -v "StrongLOH" but in this way I also exclude some lines which don't have the problem. Once I omit these lines vardict runs from the beginning till the end without any issues.
And second question: do you run vardict on bam files with or without GATK BQSR (base quality score recalibration)? I have run it for the moment on bam files without BQSR.
Thank you very much
[vardict_500l.stdout.txt](https://github.com/AstraZeneca-NGS/VarDict/files/2220077/vardict_500l.stdout.txt)

**Comment by atomiuk** [comment] 2018-08-27 13:36
Hi,
Today, I experienced the same issue with paired reads mapped against GRCh37 using the GATK4 pipeline.
I would be very helpful, if you could comment on this.
Thank you very much in advance!

Stefan

**Comment by BilyanaStoilova** [comment] 2018-09-04 16:18
Hi, I am glad someone else is experiencing the same issue, however I never got a reply from the Vardict developers what the reason was. To try to overcome it I grepped-out  the lines which were truncated using grep -v "StrongLOH" because I noticed that all truncated lines were marked with StrongLOH. This solved the problem for 50% of the files but for the rest I discovered another problem, which is even more weird - a random line within the file output from vardict (input for testsomatic.R) contained a missing value and testsomatic.R produced an empty output again. To overcome this issue, I uploaded the output from vardict into testsomatic.R and when I ran the script in R it gave an error telling that certain columns, which should contain non-negative values contained negative values (in my case missing values). Then I manually looked for the lines with the missing values and removed them with grep -v again. And after that the vardict script worked. However, this is a very inconvenient procedure, since one should manually look for and remove lines from the files and does not allow me to include vardict into a proper pipeline. I hope this is somehow useful for you and would be glad if you share your solution to the problem, if you have any. Also, I hope that the developers will be willing to comment on this post, since now it seems it is a recurrent issue. Thank you!

**Comment by chapmanb** [comment] 2018-11-06 19:44
@PolinaBevad -- is this an issue you've seen or been working on with your column fix changes? Bilyana, do you have a small reproducible case that demonstrates the issue? This would help us determine if it's a problem with only the perl version or also in java, and also try to fix more generally.

**Comment by PolinaBevad** [comment] 2018-11-07 06:53
@BilyanaStoilova, @chapmanb, hello!

Bilyana, is the error still reproduced in last versions of Vardict Java/Perl? We fixed error with columns for variants of StrongLOH type in VarDictJava 1.5.7. It is also fixed in Vardict Perl master (merged PR: https://github.com/AstraZeneca-NGS/VarDict/pull/87). We also corrected most of the errors with negative values.
If it still appears please, can you provide the test data to check the problem?

There is one error remained with the wrong number of columns - for StrongSomatic type in the case when no reference variant was found. It appears from changes in perl repo (https://github.com/AstraZeneca-NGS/VarDict/commit/82795655a5e1e00339fe4d8d0ac276d9ab4a14a5), but it appears very rarely (we still can't find public data to reproduce it, but fixes are ready to merge in Java and Perl).

**Comment by BilyanaStoilova** [comment] 2018-11-07 10:55
@PolinaBevad, @chapmanb,
Thank you very much for your replies. From what I understand it seems it might be a version issue. I am currently using vardict within a conda environment and the version I have is vardict 2018.06.21 0 bioconda. When I do conda search vardict I can see that there are newer versions available and the newest are vardict 2018.10.18 pl526r341_0 bioconda and vardict 2018.10.18 pl526r351_0  bioconda. Could you please let me know in which of the vardict perl versions in conda you fixed the error? I would prefer to update the vardict perl in conda if the error is fixed there, rather than installing the java version, if possible. Thank you.

**Comment by BilyanaStoilova** [comment] 2018-11-14 22:47
@PolinaBevad, @chapmanb,
I now tried using the conda vardict version you recommended vardict 2018.10.18 pl526r351_0. I used the paired variant calling mode and piped the commands as outlined in my post from 23 July above but I got an empty vcf file. Then I started running the vardict, testsomatic.R and var2vcf_paired.pl scripts separately in order to pinpoint where the problem was and discovered that the problem is again testsomatic.R, which gives an empty output with the error:
Error in fisher.test(matrix(c(d[i, 28], d[i, 29], d[i, 30], d[i, 31]),  : 
  all entries of 'x' must be nonnegative and finite
Execution halted
Looking into the testsomatic.R script I see that you select rows with >= 48 columns. But in my case there are missing values in some of the columns, despite having the correct number of tabs. So to overcome this, I re-wrote testsomatic.R and included the following to exclude the missing values:
b<-d[complete.cases(d), ]
d_row <- rownames(d)
b_row <- rownames(b)
diff <- d_row[!(d_row %in% b_row)]
d <- d[!(rownames(d) %in% diff),]
When I then used this modified testsomatic.R, vardict runs throughout and gives a final vcf file.
I still don't understand where these missing values are coming from and why are they generated. Therefore I also feel a bit uncomfortable to just remove these lines but I don't see any other solution for the moment. I am happy to share with you my bam files or the output from vardict if you are interested to investigate this further. Or if you think what I added to testsomatic.R is a totally legitimate solution, maybe you can include it in an updated vardict version if other people have the same problem. It would be interesting to hear what are your thoughts on this.

**Comment by PolinaBevad** [comment] 2018-11-15 10:48
@BilyanaStoilova , hello!
All columns of output must contain the data, and if there are no data, then it must at least be zero. So your solution may take place for now, but we have to find the case when such situation appears to fix it's the reason, but not the result. These columns contain coverages and counts on directions for the second variant, so maybe some values here are wrongly calculated.
Could you please send these BAM files and region which produce output with missing values to email polina_bevad@epam.com? I will check them to see if we can fix this quickly or need some kind of research.

**Comment by PolinaBevad** [comment] 2019-06-06 06:16
@BilyanaStoilova, hello!

Thank you for posting these issues! All was fixed and now available in the new release (1.6). 
I will close this one, but let me know if you will have any other questions!

**Closed by PolinaBevad** 2019-06-06 06:16 UTC
