### ISSUE TITLE
Deletion not detected by VarDict

### ISSUE THREAD

**Issue by smerella** [AstraZeneca-NGS/VarDict#55] opened 2017-11-21 14:37 UTC
Dear all, 
I am using VarDict in a sample with known genotype. The sample was sequenced with an Illumina TruSight custom amplicon for BRCA1/2 on a MiSeq sequencer. 
We know it has a deletion of 70bp on BRCA1 gene but VarDict does not detect it (while HaplotypeCaller yes).  I generated the 8 columns bed file as suggested starting from the Target section of Illumina Manifest, here some lines as example 

```
chr13   32890519        32890777        BRCA2   0       +       32890547        32890714
chr13   32893133        32893406        BRCA2   0       +       32893163        32893512
chr13   32893349        32893611        BRCA2   0       -       32893163        32893512
chr13   32899118        32899337        BRCA2   0       +       32899162        32899371
chr13   32899280        32899538        BRCA2   0       -       32899162        32899371
chr13   32900061        32900308        BRCA2   0       +       32900187        32900800
chr13   32900253        32900530        BRCA2   0       -       32900187        32900800
chr13   32900475        32900751        BRCA2   0       +       32900187        32900800
chr13   32900697        32900969        BRCA2   0       -       32900187        32900800
chr13   32903497        32903767        BRCA2   0       +       32903529        32903679

```

Then I used vardict as suggested in the manual page, here my line:

`perl ../VarDict-master/vardict.pl -G hg19.fa -N 14-0101 -b 14-101.bam -f 0.01 -c 1 -S 2 -E 3 -g 4 -I 1000 file_for_vardic.sorted.bed | ../VarDict-master/teststrandbias.R | ../VarDict-master/var2vcf_valid.pl -N 14-0101 -E  > 14-101_vardict.vcf`

But the deletion is not presente in the final VCF, I tried using different values of -f but nothing changed..Moreover VarDict does not detect a SNV (known to be there) in the same gene.
Is there something that I am doing wrong? Am I missing something? 

Thanks for the help,

Stefania

**Comment by mjafin** [comment] 2017-11-22 08:36
Hi Stefania,
Thanks for trying out VarDict and sorry about the issues. When using VarDict in amplicon aware mode the last two columns must define the "insert" and be subsets of those values in columns 2 and 3. 

Your bed file doesn't look quite right for this purpose as the last two columns keep repeating and are not subsets of columns 2 and 3. If you are OK to run VarDict without amplicon awareness, just drop the last two columns and let me know if you see the variant?

**Comment by smerella** [comment] 2017-11-22 16:31
Hi @mjafin,
thanks for the reply!! 
You are completely right, looking at manifest file I verified that this happens when there is more than one probe for the same target. Moreover they are in opposite strand.
From the manifest file is impossible to identify the exact portion of the target that is detected from the probe, so do you think that in these cases I can use the first coordinate of the first probe and the last coordinate of the second probe for the bed file? 
For example, these are the original coordinates as declared in the manifest file:

```
chr13   32893133        32893406        BRCA2   0       +       32893163        32893512
chr13   32893349        32893611        BRCA2   0       -       32893163        32893512

```
And this is the new line:

`chr13        32893133        32893611        BRCA2   0       +       32893163        32893512
`

In this way the target is fully included in the probe section. I used the plus strand even if the second coordinate is declared in the - strand. Is this correct or the strand is an important information?

I want to use the amplicon mode because I am sure that this is an amplicon based panel. But if you think that the result is not affected by this choice I can try using the software in the other way. 

Many thanks for the support!!

Stefania

**Comment by mjafin** [comment] 2017-11-23 09:25
Hi Stefania,
I wouldn't recommend combining amplicons in the bed file into one pseudo amplicon as the algorithm was really designed to pick up individual amplicons, which may or may not overlap. In your case I suspect the problem would be that there would be reads coming from two slightly different amplicons and you're representing them as one in the bed file 

The assumption in amplicon VarDict is that for each bed line file the majority of reads coming from given amplicon will have reads starting exactly at the coordinate defined in column 2 and ending exactly at the coordinate in column 3. The algorithm then works out, based on columns 7 and 8, how many primer bases to ignore at the beginning and end of the fragment. 

Unfortunately if you don't have the exact amplicon and insert coordinates the algorithm is not going to perform as designed and you'll have false negatives most likely.

**Comment by smerella** [comment] 2017-12-19 10:18
Dear @mjafin 
Sorry for my late answer and thank you so much for the kind help.
Considering your answer I tried to correct my bed file. I considered the manifest given by the vendor. It is divided in two section, one for the target region and one for the probes. 
The part for the probes has these informations:

`Target ID       Species Build ID        Chromosome      Start Position  End Position    Strand  ULSO Sequence   DLSO Sequence   Probe Strand`

And the part of the target has these informations:

`TargetA TargetB Target Number   Species Build ID        Chromosome      Start Position  End Position    Probe Strand    Sequence`

Because I have the sequence of the specific target region and of the primers, I decided to blast all the sequences and I retrieved all the start and end points. 
In the end I generated the new file for VarDict and it looks like this:

```
chr13   32890519        32890777        BRCA2   0       .       32890545        32890750
chr13   32893133        32893406        BRCA2   0       .       32893161        32893378
chr13   32893349        32893611        BRCA2   0       .       32893377        32893584
chr13   32899118        32899337        BRCA2   0       .       32899148        32899309
chr13   32899280        32899538        BRCA2   0       .       32899307        32899511
chr13   32900061        32900308        BRCA2   0       .       32900090        32900280
chr13   32900253        32900530        BRCA2   0       .       32900280        32900502
chr13   32900475        32900751        BRCA2   0       .       32900502        32900724
chr13   32900697        32900969        BRCA2   0       .       32900724        32900942
chr13   32903497        32903767        BRCA2   0       .       32903524        32903740
chr13   32904967        32905187        BRCA2   0       .       32904993        32905160
chr13   32905133        32905363        BRCA2   0       .       32905160        32905336
chr13   32906230        32906449        BRCA2   0       .       32906258        32906419
chr13   32906382        32906601        BRCA2   0       .       32906410        32906571
chr13   32906500        32906719        BRCA2   0       .       32906529        32906691
chr13   32906662        32906883        BRCA2   0       .       32906691        32906855
chr13   32906780        32906999        BRCA2   0       .       32906807        32906969
chr13   32906892        32907112        BRCA2   0       .       32906920        32907085
chr13   32907058        32907337        BRCA2   0       .       32907085        32907311
chr13   32907284        32907522        BRCA2   0       .       32907311        32907495

```

I then run again the command:

`perl ../VarDict-master/vardict.pl -G hg19.fa -N 14-0101 -b 14-101_S1_RGSorted.bam -f 0.01 -c 1 -S 2 -E 3 -g 4 -I 15 new_vardict.sorted.bed | ../VarDict-master/teststrandbias.R | ../VarDict-master/var2vcf_valid.pl -N 14-0101 -E > 14-101_vardict.vcf`

But as before both the deletion and the SNV are not detected. 
So I suppose that my bed file is still wrong even if this time looks correct.. 
At this point, do you think that is not possible to use VardDict in this kind of amplicon panel?
Do you have any experience in using VarDict with pre-designed commercial amplicon panels?
In particular I am using Illumina TruSight Custom Amplicon for BRCA1/2 genes.

Thank you so much for the help and support!!

Stefania

**Comment by mjafin** [comment] 2017-12-19 11:33
Hi Stefania,
Sorry about the problems you're seeing. Here are a few things you could do to help debug this problem:
1. Paste a screenshot of the reads in the regions of the variants and include your current bed file as a track (IGV, NGB or similar browser) so that we can see if the variant is e.g. in only one of overlapping amplicons, close to amplicon boundary or similar
2. Try to replace `vardict.pl` with the Java version of the VarDict algorithm: https://github.com/AstraZeneca-NGS/VarDictJava - try the most recent release. It's a drop-in replacement for the perl script. 
3. If still no luck you could also provide us a slice of the bam file with the two variants and the bed file lines for the associated regions. 

We have primarily used VarDict with Qiagen GeneRead v2 panels where Qiagen provided the bed files. We haven't used TSCA much as it doesn't work with the material we have (FFPE, ctDNA) as the amplicons tend to be too long but that's an aside.

**Comment by smerella** [comment] 2018-01-05 09:43
Hi @mjafin 
sorry for my late answer. 
I tried to use the java version and I obtained same results as before. 

Here the screenshot of the IGV track including the bed file that I used to run VarDict. 
![screen shot 2017-12-19 at 15 14 38](https://user-images.githubusercontent.com/23698135/34603240-76e80602-f203-11e7-97a8-e59ed700c5e1.png)
I also included the VCF file of haplotypecaller to better understand where the deletion is.

In the zip file there are the bam file with the index for the region of interest, and the bed file used to run vardict. 
[brca.zip](https://github.com/AstraZeneca-NGS/VarDict/files/1606126/brca.zip)

Thank you so much for the kind support, I really appreciate it. 

Stefania

**Comment by mjafin** [comment] 2018-01-05 10:35
Hi @smerella, thanks for the data. I can see the deletion you mean now and indeed can't get VarDict to call it out of the box. It looks like bwa doesn't produce any indel alignments and it's all based on analysing soft clipped reads. VarDict should call these kinds of soft-clipped-only indels but it may be thrown off by a few things. I wonder if you trimmed off Illumina adapter sequences first if that would help? There seems to be quite a lot of read through (soft clipping not caused by the deletion). The other thing I noticed was that many reads are already hard clipped and have Cigars like "213H38M". I wonder what did this hard clipping in your pipeline? 

Sorry I can't be more specific.

**Comment by smerella** [comment] 2018-01-11 13:22
Hi @mjafin,
Actually I do not trim the Illumina adapters, I use the fastq files as produced by the demultiplexing step, my pipeline for the alignment is the following: 
1. bwa mem -t 2 -M hg19 R1.fastq.gz R2.fastq.gz | samtools view -Sb - | samtools sort - -T tmpfile -o result
2. BaseRecalibrator as suggested by GATK: hg19_dbSNP_148.vcf.gz, Mills_and_1000G_gold_standard.indels.hg19.sites.vcf.gz, 1000G_phase1.indels.hg19.sites.vcf.gz
3. AddOrReplaceReadGroups by picard and sort the final bam
I will try adding the step of trimming in my pipeline, do you have any suggestions? I was thinking about trimmomatic tool.

Many thanks for your help!!

**Comment by mjafin** [comment] 2018-01-11 13:43
Hi @smerella we tend to use the trimming facility in `bcl2fastq` i.e. in demultiplexing. Do you have control over the demultiplexing?

I typically run VarDict only via bcbio-nextgen and we don't perform trimming there at all. https://github.com/chapmanb/bcbio-nextgen

**Comment by PolinaBevad** [comment] 2019-05-13 14:16
@smerella, hello!
I've checked this issue and after trimming the adapters from initial BAM this deletion was detected by VarDict. The adapters were determined as parts of softclips in the realignment and they influenced on detection of such variants. I guess I can close this issue.

**Closed by PolinaBevad** 2019-05-13 14:16 UTC
