### ISSUE TITLE
Hard coded filters in VarDict remove true variant calls

### ISSUE THREAD

**Issue by gabeng** [AstraZeneca-NGS/VarDict#35] opened 2017-01-19 09:33 UTC
I am trying to get to the bottom of why VarDict has some false negatives in my high-coverage amplicon samples. I noted that VarDict performs a number of filters which are documented in the VCF header:
```
##FILTER=<ID=AMPBIAS,Description="Indicate the variant has amplicon bias.">
##FILTER=<ID=Bias,Description="Strand Bias">
##FILTER=<ID=Cluster0bp,Description="Two variants are within 0 bp">
##FILTER=<ID=InGap,Description="The variant is in the deletion gap, thus likely false positive">
##FILTER=<ID=InIns,Description="The variant is adjacent to an insertion variant">
##FILTER=<ID=LongMSI,Description="The somatic variant is flanked by long A/T (>=14)">
##FILTER=<ID=MSI12,Description="Variant in MSI region with 12 non-monomer MSI or 13 monomer MSI">
##FILTER=<ID=NM4.25,Description="Mean mismatches in reads >= 4.25, thus likely false positive">
##FILTER=<ID=PASS,Description="All filters passed">
##FILTER=<ID=Q10,Description="Mean Mapping Quality Below 10">
##FILTER=<ID=SN1.5,Description="Signal to Noise Less than 1.5">
##FILTER=<ID=d3,Description="Total Depth < 3">
##FILTER=<ID=f0.1,Description="Allele frequency < 0.1">
##FILTER=<ID=p8,Description="Mean Position in Reads Less than 8">
##FILTER=<ID=pSTD,Description="Position in Reads has STD of 0">
##FILTER=<ID=q25,Description="Mean Base Quality Below 25">
##FILTER=<ID=v2,Description="Var Depth < 2">
```

Unfortunately, only a fraction of them seem to be accessible through the command line. I am particularly interested in modifying `Cluster0bp` and `NM4.25`. I assume that VarDict is not aware of phasing. I suspect `Cluster0bp` to remove variants on the second allele which are neatly called by freebayes and clearly visible to the eye like this one:
```
chr7	117199644	.	ATCT	GTCT,A
```

I wonder why `Cluster0bp` was introduced in the first place. I cannot imagine that it made much of a difference when optimizing for TP/FP ratios in gold standard data sets. Could you shine some light on that?

**Comment by mjafin** [comment] 2017-01-19 13:02
Hi @gabeng, VarDict does pay attention to whether adjacent variants are mutually exclusive or not in reads i.e. whether there is a more complex variant on the same allele. 

Both of the two options you highlight are available in `var2vcf_valid.pl` if you look at the `-c` and `-m` options. The default for `Clusterxbp` is 0 i.e. it's off

**Comment by gabeng** [comment] 2017-01-19 15:25
The variants I am referring to are located on different alleles. They are not mutually exclusive. This is quite evident when you look at the reads.
This is the output of `vardict-java`:
```
S-NA21551_S45_L001_R1_001       -       chr7    117199644       117199644       A       G       1309    638     313     353     327     311     A/G     0.4874  2;2     36.8    1       36.9    1       60.0    24.520  0.4888  0       0       1.000   1       2.8     613     1254    GCACCATTAAAGAAAATATC    TCTTTGGTGTTTCCTATGAT    chr7:117199604-117199805        SNV     2       2       0       0
S-NA21551_S45_L001_R1_001       -       chr7    117199644       117199647       ATCT    A       1128    574     292     251     296     278     T/-3    0.5089  2;2     50.5    1       38.5    1       60.0    142.500 0.5263  0.0027  1       3.000   1       1.6     570     1083    GCACCATTAAAGAAAATATC    TTGGTGTTTCCTATGATGAA    chr7:117199495-117199708        Deletion        2       2       0       0
```
Once I pipe that through
```
teststrandbias.R| var2vcf_valid.pl -N S-NA21551_S45_L001_R1_001 -E -f 0.1
```
the SNV is gone.

This is the entire command:
```
vardict-java -G /home/ubuntu/local/share/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa -f 0.1 -N S-NA21551_S45_L001_R1_001 -b /bioinf-data/10123-eval-testrun-4/work/prealign/S-NA21551_S45_L001_R1_001/S-NA21551_S45_L001_R1_001-ready.bam -c 1 -S 2 -E 3 -g 4 -Q 10 /bioinf-data/10123-eval-testrun-4/work/vardict/chr7/S-NA21551_S45_L001_R1_001-chr7_117119975_159138663-unmerged-regions-regionlimit.bed | teststrandbias.R| var2vcf_valid.pl -N S-NA21551_S45_L001_R1_001 -E -f 0.1 -c 1 > /bioinf-data/vardict-variants-1.vcf
```
The SNV should not be filtered out. Can you indicate which setting in `var2vcf_valid.pl` filters the SNV?

**Comment by gabeng** [comment] 2017-01-19 15:47
Just noted that there is an option `-A` in the (current) March 2016 version of `var2vcf_valid.pl`. I will ask Brad to bump up the version in bcbio.

**Comment by mjafin** [comment] 2017-01-19 15:50
The version in bcbio is the latest release `1.4.8` from December 2016 actually

**Comment by gabeng** [comment] 2017-01-19 16:32
I just made a `bcbio_nextgen.py upgrade -u development` and this is what appears in `manifest/python-packages.yaml`:

```
vardict:
  name: vardict
  version: 2016.02.19
vardict-java:
  name: vardict-java
  version: 1.4.8
```

The installed `var2vcf_valid.pl` is not the version from March that I can see on github.

**Comment by chapmanb** [comment] 2017-01-19 18:05
Ben and Miika -- sorry about the out of date version in bcbio. I'll bump the perl version with the `var2vcf_valid.pl` script and follow up when it's finished in chapmanb/bcbio-nextgen#1768 Thanks much for the heads up.

**Comment by gabeng** [comment] 2017-01-20 12:39
@mjafin, there is certainly a reason why you remove one of two heterozygous variant calls at a certain position. What is that? Does the `-A` switch change the performance of VarDict in your reference data sets?

**Comment by mjafin** [comment] 2017-01-20 12:52
Ben, I'd have to refer to @zhongwulai for the design decision, bear with us.

**Comment by gabeng** [comment] 2017-01-23 07:53
I was able to verify that the `-A` option retains my verified SNP from above. Therefore, I would like to ask Brad to add this option to the bcbio `vardict` standard workflow, if this does not impact the overall FP rate in his validation.
I have another example in the same exon, though, where I need your help, since I cannot figure out why this variant is not called with the standard settings.
These are the genomic facts (NA21551): https://catalog.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM21551&PgId=166
```
ATGTGTGTGTGTGTGTGTGTGTGTTTTTTT (Reference/Wildtype)
A  TGTGTGTGTGTGTGTGTGTGTTTTTTT (Allele 1)
ATGTGTGTGTGTGTGTGTGTGTTTTTTTTT (Allele 2)
```
Depth is more than 1000x. Freebayes calls both variants correctly:

```
chr7	117188660	.	ATG	A	21700.2	PASS	AC=1;AF=0.5;AN=2;DECOMPOSED;LEN=2;NS=1;TYPE=del	GT:GQ:DP:AD:RO:QR:AO:QA:GL	1|0:127:1718:26,510,405:26:933:510,405:16471,14806:-2453.57,-1133.32,-1055.89,-1251.99,0,-1206.17
chr7	117188682	.	G	T	21700.2	PASS	AC=1;AF=0.5;AN=2;DECOMPOSED;LEN=1;NS=1;TYPE=snp	GT:GQ:DP:AD:RO:QR:AO:QA:GL	0|1:127:1718:26,510,405:26:933:510,405:16471,14806:-2453.57,-1133.32,-1055.89,-1251.99,0,-1206.17
```

Vardict only calls:
```
chr7	117188660	rs4646205	ATG	A	346	PASS	ADJAF=0.0075;AF=0.4284;AMPFLAG=0;BIAS=2:2;DP=1592;GDAMP=1;HIAF=0.4479;HICNT=654;HICOV=1460;LSEQ=AAACTCATCTTTTATTTTTG;MQ=58.2;MSI=11;MSILEN=2;NCAMP=0;NM=2.4;ODDRATIO=1.16393;PMEAN=51.8;PSTD=1;QSTD=1;QUAL=36.8;REFBIAS=346:322;RSEQ=TGTGTGTGTGTGTGTGTGTG;SAMPLE=S-NA21551_S45_L001_R1_001;SBF=0.17251;SHIFT3=21;SN=23.357;TLAMP=1;TYPE=Deletion;VARBIAS=379:303;VD=682;rs_ids=rs4646205	GT:DP:VD:AD:AF:RD:ALD	0/1:1592:682:668,682:0.4284:346,322:379,303
```
I tried to use the debug option  `-D` in `vardict-java` but I do not see any trace of the G>T call anywhere. Is there any way to figure out why this call is not made?

**Comment by gabeng** [comment] 2017-01-27 15:53
I have not found any parameter to modify the local realignment behaviour. It seems that local realignment is not working well (or not producing the desired results) in repetitive regions. I will turn it off in for my samples. What would be the global impact of using `-k 0` with vardict-java in validation testing against GiB, @chapmanb?

**Comment by chapmanb** [comment] 2017-01-27 18:50
Ben;
I haven't benchmarked globally with local realignment turned off. My assumption would be that this would hurt generally as it's going to ruin resolution in other less repetitive regions, but we could look along with the `-A` suggestion. I'm running DREAM synthetic 4 validation benchmarks now with the current version as a baseline to start to test these tweaks.

If you could share a slice of the BAM file in your problem region as a reproducible case, I think it would be worth looking at the underlying issue and trying to fix that. Would that be possible?

**Comment by gabeng** [comment] 2017-01-28 09:53
Brad,
thanks for running the validation so quickly. I was wondering if there is a parameter to tell vardict to consider a longer stretch of bp for local re-alignment. This may impact performance but may solve the issue at least for repetitive regions of certain length. Just a thought from an outsider without any knowledge of the code.
I would be happy to share a slice of the BAM file. Where should I put it?

**Comment by mjafin** [comment] 2017-01-28 10:18
Just a quick note, I would be cautious about changing global settings based on a single missed variant

**Comment by gabeng** [comment] 2017-01-28 10:41
You are absolutely right about being cautious. That is why Brad's validation is so valuable. 
Regarding my specific application I am left with two choices: use both options mentioned above with vardict or go back to freebayes. Unfortunately, the missed variant is clinically relevant. When I have some time, I will take a broader look at variants where vardict and freebayes disagree.

**Comment by mjafin** [comment] 2017-01-28 11:10
Hi @gabeng, FreeBayes is absolutely brilliant for germline whereas VarDict was always tuned for cancer applications. FreeBayes isn't that great with longer, more complex and subclonal indels you see in tumours. 

For your specific case and why the realigner dismisses the other variant we'd need to hear back from @zhongwulai, however I know he's been up to his eyeballs with other stuff lately.

**Comment by chapmanb** [comment] 2017-02-01 18:24
Ben and Miika;
Thanks again for this discussion. We ran whole genome validation of these options against NA12878 (http://imgur.com/a/SF2a8) and have a comparison to discuss from:

![Vardict 35 validation](http://i.imgur.com/A6XEkDB.png)

The `-A` option provides a slight increase in sensitivity with corresponding small decrease in precision but does not have a big impact. Based on Ben's analysis above, it's worth adding this as a default.

The `-k 0` option is more difficult. It does help with SNP sensitivity, likely in cases like Ben identified above, but it makes indel resolution much worse. The best thing to do here is to try and debug the problem case and see if there's a fix we can get into VarDict to do better at resolving these variants. Ben, how big are your sliced BAM files? You can likely attach them to a message or upload to S3 as a way to share them. Would that work?

**Comment by gabeng** [comment] 2017-02-01 18:46
Brad, thanks for the performance comparison, that's very interesting. I will share the data through S3 by early next week, since I am travelling.

**Comment by PolinaBevad** [comment] 2019-05-28 10:49
@gabeng, hello!
I guess I can close this issue because it is quite old, and local realignment was significantly changed from that time. There is also `-X` option in VarDict to change the extension of bp to look for mismatches after insertion or deletion (default is 2), that can be helpful.
If there are still some problems with local realignment on your samples, please reopen this issue and we can work on it.
Thank you!

**Closed by PolinaBevad** 2019-05-28 10:49 UTC
