### ISSUE TITLE
Empty VCF file

### ISSUE THREAD

**Issue by AlisonKennedy** [AstraZeneca-NGS/VarDict#63] opened 2018-05-15 13:02 UTC
Hi, 

I'm attempting to use VarDict in single sample mode for analysis of a targeted gene panel, approximately 300Kb in size generated on an Illumina NextSeq. However when following the workflow I get an empty VCF file with only the headers and no variants. Other variant callers like Varscan2 and Mutect2 have been used successfully. 

I am using BWA mem for alignment.

Below is an examples of the command I'm using:

vardict -G Homo_sapiens_assembly38.fasta -N BEL037 -b BEL037.rg.bam -c 1 -S 2 -E 3 -g 4 -D -F 0 -f 0.01 initial_design.bed | VarDict-master/teststrandbias.R | VarDict-master/var2vcf_valid.pl -N BEL037 -f 0.01 > BEL037_vardict.vcf

I have also tried using bioconda and the vardict-java and get the same problem.

Any help or advice would be greatly appreciated!

**Comment by mjafin** [comment] 2018-05-15 13:18
Hi @AK-WIMM,
I wonder what you bed file looks like? Is it a small-ish subset of the targeted regions or all in one? VarDict expects externally split bed regions and scales not by depth but by width of the regions.

**Comment by mjafin** [comment] 2018-05-15 13:27
Can you try generating a bed file with just a handful lines, such where you know there are variants present and try again? The fourth column should be fine if it's empty (but does have the tab in between 3rd and 4th columns), although I haven't tried it out. You could always try to see if it actually makes a difference by including/excluding lines with an empty 4th column.

**Comment by AK-WIMM** [comment] 2018-05-15 14:38
I have generate a BED file including only the regions covered in the gene TP53.

chr17   7666176 7666276 TP53
chr17   7669601 7669701 TP53
chr17   7670608 7670715 TP53
chr17   7673194 7673374 TP53
chr17   7673521 7673621 TP53
chr17   7673700 7673837 TP53
chr17   7674180 7674290 TP53
chr17   7674858 7674971 TP53
chr17   7675052 7675236 TP53
chr17   7675993 7676272 TP53
chr17   7676342 7676442 TP53
chr17   7676507 7676607 TP53

When using the following command I get the following lines in a text file.

vardict -G Homo_sapiens_assembly38.fasta -f 0.01 -N BEL037 -b BEL037.rg.bam -c 1 -S 2 -E 3 -g 4 -F 0 -h initial_design_TP53.bed > BEL037_P53.txt

Sample  Gene    Chr     Start   End     Ref     Alt     Depth   AltDepth        RefFwdReads     RefRevReads     AltFwdReads     AltRevReads     Genotype        AF      Bias    PMean   PStd    QMean   QStd    5pFlankSeq      3pFlankSeq
BEL037  TP53    chr17   7674220 7674220 C       T       1218    17      562     639     6       11      C/T     0.0140  2;2     19.3    1       36.0    0       60.0    34.000  0.0140  0       0       2.000   1       1.1     17      1211    TGATGGTGAGGATGGGCCTC    GGTTCATGCCGCCCATGCAG    chr17:7674180-7674290   SNV
BEL037  TP53    chr17   7675062 7675086 C       CTGAGCGCTGCTCAGATAGCGATGG       913     16      462     434     11      5       C/+24   0.0175  2;2     16.2    1       34.6    1       60.0    32.000  0.0175  0.0175  5       2.000   1       0.0     16      913     CAGCTGCTCACCATCGCTAT    TGAGCAGCGCTCATGGTGGG    chr17:7675052-7675236   Insertion
BEL037  TP53    chr17   7676011 7676011 T       C       1100    828     158     113     492     336     T/C     0.7527  2;2     18.7    1       35.6    1       60.0    117.286 0.7525  0       0       2.000   1       1.1     821     1091    GACCGTGCAAGTCACAGACT    GGCTGTCCCAGAATGCAAGA    chr17:7675993-7676272   SNV
BEL037  TP53    chr17   7676154 7676154 G       C       1120    179     482     457     96      83      G/C     0.1598  2;2     18.8    1       32.9    1       60.0    8.421   0.1465  0       2       6.000   1       1.1     160     1092    CTGCTGGTGCAGGGGCCACG    GGGGAGCAGCCTCTGGCATT    chr17:7675993-7676272   SNV
BEL037  TP53    chr17   7676406 7676406 G       T       1090    153     515     421     85      68      G/T     0.1404  2;2     18.2    1       35.4    1       60.0    306.000 0.1422  0       0       3.000   1       1.2     153     1076    ACGTTGTTTTCAGGAAGTCT    AAAGACAAGAGCAGAAAGTC    chr17:7676342-7676442   SNV
BEL037_P53.txt (END) 

However if I pipe this to the teststrandbias.R and the var2vcf_valid.pl I get an empty VCF file. If I bypass the R-script and go straight to vcf generation I get the following errors.

Argument "TGATGGTGAGGATGGGCCTC" isn't numeric in numeric lt (<) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 137, <> line 6.
Argument "CAGCTGCTCACCATCGCTAT" isn't numeric in numeric lt (<) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 137, <> line 6.
Argument "GACCGTGCAAGTCACAGACT" isn't numeric in numeric lt (<) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 137, <> line 6.
Argument "CTGCTGGTGCAGGGGCCACG" isn't numeric in numeric lt (<) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 137, <> line 6.
Argument "ACGTTGTTTTCAGGAAGTCT" isn't numeric in numeric lt (<) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 137, <> line 6.
Argument "Start" isn't numeric in sort at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 111, <> line 6.
Argument "RefRevReads" isn't numeric in addition (+) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 127, <> line 6.
Argument "RefFwdReads" isn't numeric in addition (+) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 127, <> line 6.
Argument "3pFlankSeq" isn't numeric in numeric lt (<) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 130, <> line 6.
Argument "Depth" isn't numeric in numeric lt (<) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 134, <> line 6.
Use of uninitialized value $hiaf in multiplication (*) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 135, <> line 6.
Use of uninitialized value $hicnt in multiplication (*) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 135, <> line 6.
Use of uninitialized value $hicnt in numeric lt (<) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 137, <> line 6.
Use of uninitialized value $hiaf in multiplication (*) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 138, <> line 6.
Use of uninitialized value $hicnt in multiplication (*) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 138, <> line 6.
Argument "AF" isn't numeric in numeric lt (<) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 140, <> line 6.
Argument "PMean" isn't numeric in numeric lt (<) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 141, <> line 6.
Argument "PStd" isn't numeric in numeric eq (==) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 142, <> line 6.
Argument "QMean" isn't numeric in numeric lt (<) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 143, <> line 6.
Use of uninitialized value $mapq in numeric lt (<) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 144, <> line 6.
Use of uninitialized value $sn in numeric lt (<) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 145, <> line 6.
Use of uninitialized value $nm in numeric gt (>) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 147, <> line 6.
Use of uninitialized value $msi in numeric gt (>) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 148, <> line 6.
Use of uninitialized value $msi in numeric ge (>=) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 148, <> line 6.
Use of uninitialized value $hiaf in numeric lt (<) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 151, <> line 6.
Use of uninitialized value $msilen in numeric eq (==) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 155, <> line 6.
Use of uninitialized value $hiaf in numeric le (<=) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 156, <> line 6.
Use of uninitialized value $msi in numeric ge (>=) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 156, <> line 6.
Use of uninitialized value $hiaf in numeric le (<=) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 158, <> line 6.
Use of uninitialized value $msi in numeric ge (>=) at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 158, <> line 6.
Argument "AltDepth" isn't numeric in log at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 171, <> line 6.
Can't take log of 0 at /t1-data/user/akennedy/exome_pipeline_2/VarDict-master/var2vcf_valid.pl line 171, <> line 6.

**Comment by ALFLAG** [comment] 2019-03-12 14:17
Hello @PolinaBevad ,
I would like to talk about this problem.
In my case, I am using vardict-java (1.5.8), but the problem is identical. The output from vardict-java is OK and the output from teststrandbias.R script is OK aswell. BUT, after process data through var2vcf_valid.pl, the output file only contain the vcf header. Which is not correct because the teststrandbias.R output does contain variants locations.

here the command line I'm using for the var2vcf_valid.pl script:
```cat input | var2vcf_valid.pl -N aligned_ech -f 0.01 -E > final_output```

you will find two input files I generated with the teststrandbias.R script,

[A61Es.txt](https://github.com/AstraZeneca-NGS/VarDict/files/2957195/A61Es.txt)
[C66Cb1.txt](https://github.com/AstraZeneca-NGS/VarDict/files/2957196/C66Cb1.txt)

the one named A61Es is OK after processed through var2vcf, but the seconde named C66Cb1 is not.
What are the differencies between this two file ? Why can't I succesfully generate a correct vcf_file ?

Thanks in advance for your help.

Alexandre

**Comment by ALFLAG** [comment] 2019-03-13 08:07
Solution to my problem was found over there by Polina
https://github.com/AstraZeneca-NGS/VarDictJava/issues/200

That's all for me!
Alexandre

**Comment by PolinaBevad** [comment] 2019-04-17 13:46
@AlisonKennedy, hello!
Because there was no reply, I will close the issue. Please, reopen it, if the problem still appears.
Thank you!

**Closed by PolinaBevad** 2019-04-17 13:46 UTC
